### PR TITLE
Added package.json for NPM

### PR DESCRIPTION
**Pull request by herkyl**
Added `package.json` so you can submit this into npm. I tested it by npm installing from Github and it works.

### CODE REVIEW

**Comment by fafournier** [comment]
That, would be awesome to have!

**Comment by herkyl** [comment]
@wbond could you merge this please?

**Comment by wbond** [comment]
@herkyl Are you interested in helping maintain this library? Currently I am overloaded and semi-burnt-out with open source. I can add you as a contributor and you can deal with NPM stuff and any other changes you see fit?

**Comment by herkyl** [comment]
@wbond sure I can take over the PRs, since I'm using this in production :)

**Comment by herkyl** [comment]
Thanks @wbond

**Comment by wbond** [comment]
Let me know if you want travis or some other sort of CI set up.

**Comment by herkyl** [comment]
Sure, lets dig into this when there are more commits, right now it is working well for me as it is 👍

**Pull request merged**
